[workspace]
resolver = "2"
members = [ ".", "rapido-core", "rapido-api", "examples/*"]
default-members = [ ".", "rapido-core", "rapido-api", "examples/*"]

[package]
name = "rapido"
version = "0.0.3"
description = "api prototyping"
authors = ["c0d3x42@gmail.com"]
edition = "2021"
license = "MIT"
repository = "https://github.com/c0d3x42/rapido"
publish = true


[lib]
name = "rapido"


[dependencies]
rapido-core = { path = './rapido-core' }

[workspace.dependencies]
anyhow      = { version = "1.0.93" }
sea-query = "0.32.0"
serde_json = { version = "1.0.133", features = ["indexmap"] }
serde = { version = "1.0.215", features = ["derive", "rc"] }
serde_with = "3.11.0"
sqlx = { version = "0.8.2", features = ["runtime-async-std", "sqlite"] }
thiserror = { version="1"}
tracing = { version="0.1.41"}
