[package]
name = "rapi"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.13.0", features = ["attributes"] }
sea-query = "0.31.0"
serde = { version = "1.0.210", features = ["derive", "rc"] }
serde_json = { version = "1.0.128", features = ["indexmap"] }
sqlx = { version = "0.8.2", features = ["runtime-async-std", "sqlite"] }
