//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::{entity::prelude::*, FromJsonQueryResult };
use serde::{Deserialize, Serialize};
use rapido_core::{component::ComponentSchema, ddl::TableDefinition};

#[derive(Clone, Debug, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "component")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: Option<String>,

    pub name: String,

    #[sea_orm(column_type = "JsonBinary")]
    pub content: ComponentWrapper
}

impl Model {
    pub fn name(&self) -> &str {
        &self.name
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

#[derive(Debug,Serialize,Deserialize, FromJsonQueryResult,Clone )]
pub struct ComponentWrapper(pub(crate) TableDefinition);
impl ComponentWrapper {
    pub fn collection_name(&self) -> &str{
        &self.0.table_name.0
    }
}

impl PartialEq for ComponentWrapper {
    fn eq(&self, other: &Self) -> bool {
        false
    }
}